apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fookie.fullname" . }}-database
  labels:
    {{- include "fookie.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.database.url | quote }}
