{{- if .Values.observability.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fookie.fullname" . }}-server
  labels:
    {{- include "fookie.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      {{- include "fookie.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
