services:
  fookie-server:
    environment:
      SCHEMA_PATH: /app/demo/schema.fql
      FOOKEE_ADMIN_KEY: change_me_local_admin
    volumes:
      - .:/app/demo:ro
  fookie-worker:
    environment:
      SCHEMA_PATH: /app/demo/schema.fql
    volumes:
      - .:/app/demo:ro
